// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessHistory struct {
	ID          int32
	KeyID       pgtype.Int4
	DeviceID    pgtype.Int4
	UserID      pgtype.Int4
	AccessTime  pgtype.Timestamp
	Result      pgtype.Text
	Description pgtype.Text
}

type Apartment struct {
	ID          int32
	Address     string
	Number      pgtype.Text
	Description pgtype.Text
	OwnerID     pgtype.Int4
	CreatedAt   pgtype.Timestamp
}

type ApartmentResident struct {
	ID           int32
	ApartmentID  pgtype.Int4
	UserID       pgtype.Int4
	ResidentType pgtype.Text
	IsActive     pgtype.Bool
	Since        pgtype.Timestamp
}

type Device struct {
	ID           int32
	SerialNumber string
	Model        pgtype.Text
	ApartmentID  pgtype.Int4
	SipAccountID pgtype.Int4
	Status       pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type DeviceLog struct {
	ID       int32
	DeviceID pgtype.Int4
	LogTime  pgtype.Timestamp
	LogLevel pgtype.Text
	Message  pgtype.Text
	Payload  []byte
}

type Event struct {
	ID          int32
	DeviceID    pgtype.Int4
	EventType   string
	UserID      pgtype.Int4
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type Key struct {
	ID          int32
	KeyCode     string
	KeyType     pgtype.Text
	OwnerID     pgtype.Int4
	IsActive    pgtype.Bool
	IssuedAt    pgtype.Timestamp
	ValidFrom   pgtype.Timestamp
	ValidTo     pgtype.Timestamp
	Description pgtype.Text
}

type Medium struct {
	ID        int32
	EventID   pgtype.Int4
	FilePath  string
	MediaType pgtype.Text
	CreatedAt pgtype.Timestamp
}

type PasswordResetToken struct {
	ID        int32
	UserID    pgtype.Int4
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type PhoneVerificationToken struct {
	Phone            string
	VerificationCode string
	ExpiresAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
}

type RefreshToken struct {
	ID        int32
	UserID    int32
	Token     string
	Jti       pgtype.Text
	ExpiresAt pgtype.Timestamp
}

type SipAccount struct {
	ID        int32
	Username  string
	Password  string
	Server    pgtype.Text
	Port      pgtype.Int4
	Protocol  pgtype.Text
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	Email        string
	Phone        string
	Role         pgtype.Text
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Timestamp
	FirstName    pgtype.Text
	LastName     pgtype.Text
	AvatarUrl    pgtype.Text
}
